### ISSUE TITLE
[PE-D] Repeated fields

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T11-4/tp#146]
It is possible for the add command to take multiple of the same field (not just tags). For example: 

`add n/Jacob Ng n/ Not Jacob d/2020-10-13 t/1300-1400 l/The Deck`

When this happens only the latest field is taken. However, this would likely have been a mistake by the user and should display an error message rather than continuing as if everything is fine.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: ryanongra/ped#10

**Comment by ruthpohrp** [comment]
This is noted in the User Guide under `5. Commands and their Features`, and as such nothing needs to be changed. However, I will leave the issue open for now just in case anyone has any objections to just closing this.
