### ISSUE TITLE
[PE-D] Dashes not allowed for names

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T11-4/tp#148]
Dashes or hyphens `-` are not allowed in names even though they are common character in a name.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: ryanongra/ped#11

**Comment by ruthpohrp** [comment]
I'm not sure if we can implement this as a feature, but for now I've added it as a note under User Guide under 5.1 Adding a Consultation Event : `add` that DukePro(f) doesn't accept entries with `-`s.
