### ISSUE TITLE
[PE-D] Invalid index shows invalid command error instead

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T11-4/tp#150]
![image.png](https://raw.githubusercontent.com/NUSmhk/ped/main/files/36a4ffff-a40b-454d-a861-34e2519d57d3.png)

Invalid index that is beyond the existing number of events should result in an invalid index error but as seen, this is giving invalid command error.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: NUSmhk/ped#7

**Comment by ruthpohrp** [comment]
This looks like it's because the number exceeds the max integer limit and should not be a valid number at all. Closed.
