### ISSUE TITLE
[PE-D] Running edit command in filtered list after running find command will switch back to full list view

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T11-4/tp#154]
Delete command still remains in filtered list but edit command switches back to list, which results in inconsistency issues. 

Steps to replicate bug:

1. Run find command on an existing event, which should show a filtered list of just the events with the keyword typed in to find.
2. Run edit command on one of the existing events shown in the GUI 
3. The filtered list will return to a full list

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: NUSmhk/ped#9

**Comment by ruthpohrp** [comment]
Prob add warning in UG about this: 
Delete deletes index of list on the right hand side (i.e. if its filtered, `delete 1` will delete the first index in the filtered list and not the entire list)
